FROM progrium/busybox
MAINTAINER Mats Engstrom <mats.engstrom@gmail.com

# For source codes (c & node)
RUN mkdir /source
VOLUME /source

# For mysql peristance
RUN mkdir /var/lib/mysql
VOLUME /var/lib/mysql

# For redis persistance
RUN mkdir /data
VOLUME /data

